#######################################################################################
# Book settings
title : Advanced topics for math and science beginners
author: Mauricio J. del Razo
logo: 'my24cell.jpg'

# Information about where the book exists on the web
description: >-
  A book introducing advanced topics for math and science beginners using Jupyter book and Jupyter notebooks.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  


#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/maojrs/topics_book
  path_to_book                : "book"
  branch                      : master

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
bibtex_bibfiles:
   - ./_bibliography/references.bib
